### ISSUE TITLE
Mob dying after spawn

### ISSUE THREAD

**Issue by GolfinhoPvP** [amokinio/miniaturepets#90]
*Short description:* Mob dying after spawn

*Long description:* I'm using the APIUtils to create custom entities, which worked at 1.5.3 plugin

*Actions to repeat / ways of reaching the bug:* just spawning by new Mob(location, container)

*Miniature Pets Dump Link:*

Code:
		mob = new Mob(location.clone().add(0, 0.5, 0), registry.get(getClass()));
		mob.clearNavigation();

[Video.zip](https://github.com/danielntech/miniaturepets/files/2847257/Video.zip)

**Comment by GolfinhoPvP** [comment]
I'm using 2.1.8

**Comment by danielntech** [comment]
Hello, this is due to our new API being different. Please examine the new documentation found here:
https://miniaturepets.net/docs

**Comment by GolfinhoPvP** [comment]
After a bunch of tests i discovered that my mob was being killed by the structure, i tried another mob (Turtle) and was successful
